### ISSUE TITLE
ImportError: No module named irc.bot

### ISSUE THREAD

**Issue by ghost** [gehaxelt/python-rss2irc#59] opened 2020-10-22 09:39 UTC
(venv) root@debian:/home/python-rss2irc# python2 feedupdater.py
Traceback (most recent call last):
  File "feedupdater.py", line 4, in <module>
    import feedparser
ImportError: No module named feedparser
(venv) root@debian:/home/python-rss2irc# python2 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot import Bot
  File "/home/python-rss2irc/bot.py", line 6, in <module>
    import irc.bot
ImportError: No module named irc.bot
(venv) root@debian:/home/python-rss2irc#

(venv) root@debian:/home/python-rss2irc# python2
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2

Any ideas why rss wont start ?

**Comment by Wibol** [comment] 2020-10-22 16:31
It seems that this does not succeed in finding the necessary modules. Have you launched the command "pip install -r requirements.txt" from within the environment?

**Comment by ghost** [comment] 2020-10-23 07:56
Yes i tryed on various vm´s with same result on all machines.

(venv) root@45365 /home/python-rss2irc # pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting backports.functools-lru-cache==1.2.1
  Downloading backports.functools_lru_cache-1.2.1-py2.py3-none-any.whl (5.9 kB)
Collecting feedparser==5.2.1
  Downloading feedparser-5.2.1.tar.bz2 (192 kB)
     |################################| 192 kB 1.8 MB/s
Collecting inflect==0.2.5
  Downloading inflect-0.2.5-py2.py3-none-any.whl (58 kB)
     |################################| 58 kB 4.9 MB/s
Collecting irc==14.2
  Downloading irc-14.2-py2.py3-none-any.whl (75 kB)
     |################################| 75 kB 5.5 MB/s
Collecting jaraco.classes==1.3
  Downloading jaraco.classes-1.3-py2.py3-none-any.whl (4.6 kB)
Collecting jaraco.collections==1.3.2
  Downloading jaraco.collections-1.3.2-py2.py3-none-any.whl (9.0 kB)
Collecting jaraco.functools==1.11
  Downloading jaraco.functools-1.11-py2.py3-none-any.whl (5.7 kB)
Collecting jaraco.itertools==1.7.1
  Downloading jaraco.itertools-1.7.1-py2.py3-none-any.whl (9.8 kB)
Collecting jaraco.logging==1.3.1
  Downloading jaraco.logging-1.3.1-py2.py3-none-any.whl (5.1 kB)
Collecting jaraco.stream==1.1
  Downloading jaraco.stream-1.1-py2.py3-none-any.whl (5.5 kB)
Collecting jaraco.text==1.6.3
  Downloading jaraco.text-1.6.3-py2.py3-none-any.whl (5.9 kB)
Collecting more-itertools==2.2
  Downloading more-itertools-2.2.tar.gz (19 kB)
Collecting python-dateutil==2.5.3
  Downloading python_dateutil-2.5.3-py2.py3-none-any.whl (201 kB)
     |################################| 201 kB 5.9 MB/s
Collecting pytz==2016.4
  Downloading pytz-2016.4-py2.py3-none-any.whl (480 kB)
     |################################| 480 kB 5.8 MB/s
Collecting six==1.10.0
  Downloading six-1.10.0-py2.py3-none-any.whl (10 kB)
Collecting sqlite3worker
  Cloning https://github.com/palantir/sqlite3worker to /tmp/pip-install-02Uj2I/sqlite3worker
Collecting tempora==1.4
  Downloading tempora-1.4-py2.py3-none-any.whl (7.1 kB)
ERROR: Could not find a version that satisfies the requirement TinyUrl==0.1.0 (from -r requirements.txt (line 18)) (from versions: none)
ERROR: No matching distribution found for TinyUrl==0.1.0 (from -r requirements.txt (line 18))
(venv) root@45365 /home/python-rss2irc # cp config.py.sample config.py
(venv) root@45365 /home/python-rss2irc # cp feeds.sql.sample feeds.sql
(venv) root@45365 /home/python-rss2irc # python2 feedupdater.py
Traceback (most recent call last):
  File "feedupdater.py", line 4, in <module>
    import feedparser
ImportError: No module named feedparser
(venv) root@45365 /home/python-rss2irc # python2 main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot import Bot
  File "/home/python-rss2irc/bot.py", line 6, in <module>
    import irc.bot
ImportError: No module named irc.bot

**Comment by ghost** [comment] 2020-10-26 10:49
I removed versioninfos from requirements.txt and installed Tinyurl from: https://github.com/daxeel/TinyURL-Python.git
also i added BeautifulSoup4 to requirements.txt.

Bot is running now.

**Comment by Wibol** [comment] 2021-02-10 16:30
A few days ago the same thing happened to me when I wanted to reinstall it. The problem is that the "TinyUrl" module no longer exists in the Python repository, and when a module is not available, "pip" doesn't install any. That's why it doesn't find "irc" either. I fixed it by changing the code to use the "v.gd" shortener instead, but the Pull Request still hasn't been accepted.

I have now translated the bot to Python3 and it uses the latest libraries available. I would like some users to help me test it on different systems before making the Pull Request, as this is a major change.

The Python3 edition of the bot and the new installation instructions are available at [my repository](https://github.com/Wibol/python-rss2irc). You can still use your current "feeds.sql" file, but the database needs to be recreated, so it would be advisable before running it:

`mv feeds.db feeds.db.old`

Thanks.

Translated with www.DeepL.com/Translator (free version)

**Comment by DEADC1DE** [comment] 2021-02-16 14:37
Working for me. Thanks alot @Wibol

**Comment by Wibol** [comment] 2021-02-16 17:17
> Working for me. Thanks alot @Wibol

Thanks for the feedback.

**Comment by gehaxelt** [comment] 2021-02-23 08:25
Thank you @Wibol for finding a solution! I'll close this since @Wibol's PR should have addressed the issue.

**Closed as completed by gehaxelt** 2021-02-23 08:25 UTC
